version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prisma-migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma_migrate
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/guru
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma generate"

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/guru
      PORT: 3000
    ports:
      - "3000:3000"
    command: >
      sh -c "npm run build && npm run start:prod"

volumes:
  postgres_data:
